import requests
import urllib
from bs4 import  BeautifulSoup
from urllib.parse import urlparse
from datetime import datetime
import os
from apscheduler.schedulers.blocking import BlockingScheduler

urls = [
    'http://comic.naver.com/webtoon/list.nhn?titleId=183559&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=648419&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=602910&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=679519&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=694946&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=654774&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=597478&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=694807&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=647946&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=679568&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=675554&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=624632&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=644180&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=694191&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=668723&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=687915&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=25613&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=316911&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=21815&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=658076&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=675559&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=678494&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=660025&weekday=mon',
'http://comic.naver.com/webtoon/list.nhn?titleId=25455&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=20853&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=675331&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=655744&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=119874&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=683496&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=695321&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=650304&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=682637&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=692512&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=689705&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=676695&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=654817&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=675554&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=686911&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=644180&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=602287&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=616239&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=400739&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=679569&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=686312&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=686669&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=666670&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=695768&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=626906&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=653344&weekday=tue',
'http://comic.naver.com/webtoon/list.nhn?titleId=626907&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=662774&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=667573&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=651673&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=670143&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=692510&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=694131&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=642598&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=400742&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=675554&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=665618&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=449854&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=671421&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=644180&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=459545&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=694806&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=643123&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=687610&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=689701&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=681453&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=659934&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=635174&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=169080&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=602916&weekday=wed',
'http://comic.naver.com/webtoon/list.nhn?titleId=570503&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=557672&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=679519&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=570506&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=679544&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=131385&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=693444&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=637931&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=694805&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=675554&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=693431&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=670144&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=644180&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=24965&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=657948&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=687921&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=579352&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=646358&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=652418&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=690594&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=670145&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=670131&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=160469&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=675829&weekday=thu',
'http://comic.naver.com/webtoon/list.nhn?titleId=641253&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=318995&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=675393&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=119874&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=552960&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=670149&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=668101&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=678499&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=675554&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=651664&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=644180&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=626940&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=679543&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=693429&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=551649&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=685460&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=687610&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=509094&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=644112&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=654333&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=677753&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=694803&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=169080&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=310616&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=668103&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=622643&weekday=fri',
'http://comic.naver.com/webtoon/list.nhn?titleId=597447&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=568986&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=650305&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=677536&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=670139&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=679567&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=677737&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=651673&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=642700&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=651665&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=670150&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=682637&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=679570&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=686911&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=670151&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=644180&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=64997&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=622644&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=616239&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=25613&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=659934&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=686669&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=524520&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=687137&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=664406&weekday=sat',
'http://comic.naver.com/webtoon/list.nhn?titleId=654809&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=670152&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=684435&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=557676&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=119874&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=692510&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=651617&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=642598&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=690020&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=695585&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=650292&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=675823&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=644180&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=655746&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=374974&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=243315&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=690503&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=22897&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=665170&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=686018&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=626906&weekday=sun',
'http://comic.naver.com/webtoon/list.nhn?titleId=666671',
'http://comic.naver.com/webtoon/list.nhn?titleId=654138',
'http://comic.naver.com/webtoon/list.nhn?titleId=662162',
'http://comic.naver.com/webtoon/list.nhn?titleId=679545',
'http://comic.naver.com/webtoon/list.nhn?titleId=626949',
'http://comic.naver.com/webtoon/list.nhn?titleId=612769',
'http://comic.naver.com/webtoon/list.nhn?titleId=675516',
'http://comic.naver.com/webtoon/list.nhn?titleId=690502',
'http://comic.naver.com/webtoon/list.nhn?titleId=677740',
'http://comic.naver.com/webtoon/list.nhn?titleId=597481',
'http://comic.naver.com/webtoon/list.nhn?titleId=597473',
'http://comic.naver.com/webtoon/list.nhn?titleId=660366',
'http://comic.naver.com/webtoon/list.nhn?titleId=675830',
'http://comic.naver.com/webtoon/list.nhn?titleId=640110',
'http://comic.naver.com/webtoon/list.nhn?titleId=630386',
'http://comic.naver.com/webtoon/list.nhn?titleId=629056',
'http://comic.naver.com/webtoon/list.nhn?titleId=675822',
'http://comic.naver.com/webtoon/list.nhn?titleId=670140',
'http://comic.naver.com/webtoon/list.nhn?titleId=557675',
'http://comic.naver.com/webtoon/list.nhn?titleId=674209',
'http://comic.naver.com/webtoon/list.nhn?titleId=686885',
'http://comic.naver.com/webtoon/list.nhn?titleId=657522',
'http://comic.naver.com/webtoon/list.nhn?titleId=651675',
'http://comic.naver.com/webtoon/list.nhn?titleId=548870',
'http://comic.naver.com/webtoon/list.nhn?titleId=679547',
'http://comic.naver.com/webtoon/list.nhn?titleId=597466',
'http://comic.naver.com/webtoon/list.nhn?titleId=578109',
'http://comic.naver.com/webtoon/list.nhn?titleId=680193',
'http://comic.naver.com/webtoon/list.nhn?titleId=642653',
'http://comic.naver.com/webtoon/list.nhn?titleId=677452',
'http://comic.naver.com/webtoon/list.nhn?titleId=670147',
'http://comic.naver.com/webtoon/list.nhn?titleId=665174',
'http://comic.naver.com/webtoon/list.nhn?titleId=666537',
'http://comic.naver.com/webtoon/list.nhn?titleId=685989',
'http://comic.naver.com/webtoon/list.nhn?titleId=358422',
'http://comic.naver.com/webtoon/list.nhn?titleId=682222',
'http://comic.naver.com/webtoon/list.nhn?titleId=678500',
'http://comic.naver.com/webtoon/list.nhn?titleId=409629',
'http://comic.naver.com/webtoon/list.nhn?titleId=297795',
'http://comic.naver.com/webtoon/list.nhn?titleId=682265',
'http://comic.naver.com/webtoon/list.nhn?titleId=675392',
'http://comic.naver.com/webtoon/list.nhn?titleId=654331',
'http://comic.naver.com/webtoon/list.nhn?titleId=682803',
'http://comic.naver.com/webtoon/list.nhn?titleId=400740',
'http://comic.naver.com/webtoon/list.nhn?titleId=661043',
'http://comic.naver.com/webtoon/list.nhn?titleId=530312',
'http://comic.naver.com/webtoon/list.nhn?titleId=602921',
'http://comic.naver.com/webtoon/list.nhn?titleId=646359',
'http://comic.naver.com/webtoon/list.nhn?titleId=675474',
'http://comic.naver.com/webtoon/list.nhn?titleId=680911',
'http://comic.naver.com/webtoon/list.nhn?titleId=81482',
'http://comic.naver.com/webtoon/list.nhn?titleId=643302',
'http://comic.naver.com/webtoon/list.nhn?titleId=61731',
'http://comic.naver.com/webtoon/list.nhn?titleId=663887',
'http://comic.naver.com/webtoon/list.nhn?titleId=670146',
'http://comic.naver.com/webtoon/list.nhn?titleId=669360',
'http://comic.naver.com/webtoon/list.nhn?titleId=617882',
'http://comic.naver.com/webtoon/list.nhn?titleId=669357',
'http://comic.naver.com/webtoon/list.nhn?titleId=668102',
'http://comic.naver.com/webtoon/list.nhn?titleId=656641',
'http://comic.naver.com/webtoon/list.nhn?titleId=316909',
'http://comic.naver.com/webtoon/list.nhn?titleId=654316',
'http://comic.naver.com/webtoon/list.nhn?titleId=654317',
'http://comic.naver.com/webtoon/list.nhn?titleId=628997',
'http://comic.naver.com/webtoon/list.nhn?titleId=669358',
'http://comic.naver.com/webtoon/list.nhn?titleId=675556',
'http://comic.naver.com/webtoon/list.nhn?titleId=666196',
'http://comic.naver.com/webtoon/list.nhn?titleId=423384',
'http://comic.naver.com/webtoon/list.nhn?titleId=621494',
'http://comic.naver.com/webtoon/list.nhn?titleId=660333',
'http://comic.naver.com/webtoon/list.nhn?titleId=655747',
'http://comic.naver.com/webtoon/list.nhn?titleId=655749',
'http://comic.naver.com/webtoon/list.nhn?titleId=517252',
'http://comic.naver.com/webtoon/list.nhn?titleId=640050',
'http://comic.naver.com/webtoon/list.nhn?titleId=597449',
'http://comic.naver.com/webtoon/list.nhn?titleId=551648',
'http://comic.naver.com/webtoon/list.nhn?titleId=335885',
'http://comic.naver.com/webtoon/list.nhn?titleId=546625',
'http://comic.naver.com/webtoon/list.nhn?titleId=22027',
'http://comic.naver.com/webtoon/list.nhn?titleId=644111',
'http://comic.naver.com/webtoon/list.nhn?titleId=603159',
'http://comic.naver.com/webtoon/list.nhn?titleId=662160',
'http://comic.naver.com/webtoon/list.nhn?titleId=656469',
'http://comic.naver.com/webtoon/list.nhn?titleId=646568',
'http://comic.naver.com/webtoon/list.nhn?titleId=642604',
'http://comic.naver.com/webtoon/list.nhn?titleId=551650',
'http://comic.naver.com/webtoon/list.nhn?titleId=661085',
'http://comic.naver.com/webtoon/list.nhn?titleId=578108',
'http://comic.naver.com/webtoon/list.nhn?titleId=609480',
'http://comic.naver.com/webtoon/list.nhn?titleId=511447',
'http://comic.naver.com/webtoon/list.nhn?titleId=652122',
'http://comic.naver.com/webtoon/list.nhn?titleId=622646',
'http://comic.naver.com/webtoon/list.nhn?titleId=666516',
'http://comic.naver.com/webtoon/list.nhn?titleId=642599',
'http://comic.naver.com/webtoon/list.nhn?titleId=667010',
'http://comic.naver.com/webtoon/list.nhn?titleId=647948',
'http://comic.naver.com/webtoon/list.nhn?titleId=515883',
'http://comic.naver.com/webtoon/list.nhn?titleId=658823',
'http://comic.naver.com/webtoon/list.nhn?titleId=666673',
'http://comic.naver.com/webtoon/list.nhn?titleId=626939',
'http://comic.naver.com/webtoon/list.nhn?titleId=423383',
'http://comic.naver.com/webtoon/list.nhn?titleId=651667',
'http://comic.naver.com/webtoon/list.nhn?titleId=628876',
'http://comic.naver.com/webtoon/list.nhn?titleId=608263',
'http://comic.naver.com/webtoon/list.nhn?titleId=654318',
'http://comic.naver.com/webtoon/list.nhn?titleId=22045',
'http://comic.naver.com/webtoon/list.nhn?titleId=51007',
'http://comic.naver.com/webtoon/list.nhn?titleId=655277',
'http://comic.naver.com/webtoon/list.nhn?titleId=662898',
'http://comic.naver.com/webtoon/list.nhn?titleId=628998',
'http://comic.naver.com/webtoon/list.nhn?titleId=570505',
'http://comic.naver.com/webtoon/list.nhn?titleId=537989',
'http://comic.naver.com/webtoon/list.nhn?titleId=655748',
'http://comic.naver.com/webtoon/list.nhn?titleId=602923',
'http://comic.naver.com/webtoon/list.nhn?titleId=414609',
'http://comic.naver.com/webtoon/list.nhn?titleId=509092',
'http://comic.naver.com/webtoon/list.nhn?titleId=630832',
'http://comic.naver.com/webtoon/list.nhn?titleId=608261',
'http://comic.naver.com/webtoon/list.nhn?titleId=632341',
'http://comic.naver.com/webtoon/list.nhn?titleId=619329',
'http://comic.naver.com/webtoon/list.nhn?titleId=657934',
'http://comic.naver.com/webtoon/list.nhn?titleId=632344',
'http://comic.naver.com/webtoon/list.nhn?titleId=619935',
'http://comic.naver.com/webtoon/list.nhn?titleId=638994',
'http://comic.naver.com/webtoon/list.nhn?titleId=507638',
'http://comic.naver.com/webtoon/list.nhn?titleId=186811',
'http://comic.naver.com/webtoon/list.nhn?titleId=647947',
'http://comic.naver.com/webtoon/list.nhn?titleId=612767',
'http://comic.naver.com/webtoon/list.nhn?titleId=635989',
'http://comic.naver.com/webtoon/list.nhn?titleId=622648',
'http://comic.naver.com/webtoon/list.nhn?titleId=497180',
'http://comic.naver.com/webtoon/list.nhn?titleId=652466',
'http://comic.naver.com/webtoon/list.nhn?titleId=503253',
'http://comic.naver.com/webtoon/list.nhn?titleId=622640',
'http://comic.naver.com/webtoon/list.nhn?titleId=460688',
'http://comic.naver.com/webtoon/list.nhn?titleId=644182',
'http://comic.naver.com/webtoon/list.nhn?titleId=653857',
'http://comic.naver.com/webtoon/list.nhn?titleId=629055',
'http://comic.naver.com/webtoon/list.nhn?titleId=528785',
'http://comic.naver.com/webtoon/list.nhn?titleId=632337',
'http://comic.naver.com/webtoon/list.nhn?titleId=651663',
'http://comic.naver.com/webtoon/list.nhn?titleId=643607',
'http://comic.naver.com/webtoon/list.nhn?titleId=26108',
'http://comic.naver.com/webtoon/list.nhn?titleId=563785',
'http://comic.naver.com/webtoon/list.nhn?titleId=632705',
'http://comic.naver.com/webtoon/list.nhn?titleId=608265',
'http://comic.naver.com/webtoon/list.nhn?titleId=626946',
'http://comic.naver.com/webtoon/list.nhn?titleId=641580',
'http://comic.naver.com/webtoon/list.nhn?titleId=440244',
'http://comic.naver.com/webtoon/list.nhn?titleId=389848',
'http://comic.naver.com/webtoon/list.nhn?titleId=651670',
'http://comic.naver.com/webtoon/list.nhn?titleId=374973',
'http://comic.naver.com/webtoon/list.nhn?titleId=652403',
'http://comic.naver.com/webtoon/list.nhn?titleId=622641',
'http://comic.naver.com/webtoon/list.nhn?titleId=639080',
'http://comic.naver.com/webtoon/list.nhn?titleId=639604',
'http://comic.naver.com/webtoon/list.nhn?titleId=452116',
'http://comic.naver.com/webtoon/list.nhn?titleId=546805',
'http://comic.naver.com/webtoon/list.nhn?titleId=395442',
'http://comic.naver.com/webtoon/list.nhn?titleId=597480',
'http://comic.naver.com/webtoon/list.nhn?titleId=632342',
'http://comic.naver.com/webtoon/list.nhn?titleId=602922',
'http://comic.naver.com/webtoon/list.nhn?titleId=502673',
'http://comic.naver.com/webtoon/list.nhn?titleId=316914',
'http://comic.naver.com/webtoon/list.nhn?titleId=616238',
'http://comic.naver.com/webtoon/list.nhn?titleId=613076',
'http://comic.naver.com/webtoon/list.nhn?titleId=644117',
'http://comic.naver.com/webtoon/list.nhn?titleId=471283',
'http://comic.naver.com/webtoon/list.nhn?titleId=632330',
'http://comic.naver.com/webtoon/list.nhn?titleId=557674',
'http://comic.naver.com/webtoon/list.nhn?titleId=563784',
'http://comic.naver.com/webtoon/list.nhn?titleId=537990',
'http://comic.naver.com/webtoon/list.nhn?titleId=626938',
'http://comic.naver.com/webtoon/list.nhn?titleId=579416',
'http://comic.naver.com/webtoon/list.nhn?titleId=607486',
'http://comic.naver.com/webtoon/list.nhn?titleId=521533',
'http://comic.naver.com/webtoon/list.nhn?titleId=622647',
'http://comic.naver.com/webtoon/list.nhn?titleId=608258',
'http://comic.naver.com/webtoon/list.nhn?titleId=613933',
'http://comic.naver.com/webtoon/list.nhn?titleId=616883',
'http://comic.naver.com/webtoon/list.nhn?titleId=635187',
'http://comic.naver.com/webtoon/list.nhn?titleId=609477',
'http://comic.naver.com/webtoon/list.nhn?titleId=604146',
'http://comic.naver.com/webtoon/list.nhn?titleId=505715',
'http://comic.naver.com/webtoon/list.nhn?titleId=511444',
'http://comic.naver.com/webtoon/list.nhn?titleId=631780',
'http://comic.naver.com/webtoon/list.nhn?titleId=626904',
'http://comic.naver.com/webtoon/list.nhn?titleId=507637',
'http://comic.naver.com/webtoon/list.nhn?titleId=325631',
'http://comic.naver.com/webtoon/list.nhn?titleId=551647',
'http://comic.naver.com/webtoon/list.nhn?titleId=409630',
'http://comic.naver.com/webtoon/list.nhn?titleId=537991',
'http://comic.naver.com/webtoon/list.nhn?titleId=608259',
'http://comic.naver.com/webtoon/list.nhn?titleId=81483',
'http://comic.naver.com/webtoon/list.nhn?titleId=622639',
'http://comic.naver.com/webtoon/list.nhn?titleId=483796',
'http://comic.naver.com/webtoon/list.nhn?titleId=622638',
'http://comic.naver.com/webtoon/list.nhn?titleId=579414',
'http://comic.naver.com/webtoon/list.nhn?titleId=602925',
'http://comic.naver.com/webtoon/list.nhn?titleId=532057',
'http://comic.naver.com/webtoon/list.nhn?titleId=563787',
'http://comic.naver.com/webtoon/list.nhn?titleId=528781',
'http://comic.naver.com/webtoon/list.nhn?titleId=570504',
'http://comic.naver.com/webtoon/list.nhn?titleId=570502',
'http://comic.naver.com/webtoon/list.nhn?titleId=602930',
'http://comic.naver.com/webtoon/list.nhn?titleId=26316',
'http://comic.naver.com/webtoon/list.nhn?titleId=592721',
'http://comic.naver.com/webtoon/list.nhn?titleId=599232',
'http://comic.naver.com/webtoon/list.nhn?titleId=570696',
'http://comic.naver.com/webtoon/list.nhn?titleId=530311',
'http://comic.naver.com/webtoon/list.nhn?titleId=578105',
'http://comic.naver.com/webtoon/list.nhn?titleId=579417',
'http://comic.naver.com/webtoon/list.nhn?titleId=546626',
'http://comic.naver.com/webtoon/list.nhn?titleId=507276',
'http://comic.naver.com/webtoon/list.nhn?titleId=590252',
'http://comic.naver.com/webtoon/list.nhn?titleId=521504',
'http://comic.naver.com/webtoon/list.nhn?titleId=293523',
'http://comic.naver.com/webtoon/list.nhn?titleId=495498',
'http://comic.naver.com/webtoon/list.nhn?titleId=546624',
'http://comic.naver.com/webtoon/list.nhn?titleId=551651',
'http://comic.naver.com/webtoon/list.nhn?titleId=462900',
'http://comic.naver.com/webtoon/list.nhn?titleId=423392',
'http://comic.naver.com/webtoon/list.nhn?titleId=557678',
'http://comic.naver.com/webtoon/list.nhn?titleId=578106',
'http://comic.naver.com/webtoon/list.nhn?titleId=597593',
'http://comic.naver.com/webtoon/list.nhn?titleId=414611',
'http://comic.naver.com/webtoon/list.nhn?titleId=471286',
'http://comic.naver.com/webtoon/list.nhn?titleId=604147',
'http://comic.naver.com/webtoon/list.nhn?titleId=293520',
'http://comic.naver.com/webtoon/list.nhn?titleId=471181',
'http://comic.naver.com/webtoon/list.nhn?titleId=481793',
'http://comic.naver.com/webtoon/list.nhn?titleId=546750',
'http://comic.naver.com/webtoon/list.nhn?titleId=89097',
'http://comic.naver.com/webtoon/list.nhn?titleId=563782',
'http://comic.naver.com/webtoon/list.nhn?titleId=517773',
'http://comic.naver.com/webtoon/list.nhn?titleId=452117',
'http://comic.naver.com/webtoon/list.nhn?titleId=563786',
'http://comic.naver.com/webtoon/list.nhn?titleId=528784',
'http://comic.naver.com/webtoon/list.nhn?titleId=507275',
'http://comic.naver.com/webtoon/list.nhn?titleId=423377',
'http://comic.naver.com/webtoon/list.nhn?titleId=460687',
'http://comic.naver.com/webtoon/list.nhn?titleId=325630',
'http://comic.naver.com/webtoon/list.nhn?titleId=310617',
'http://comic.naver.com/webtoon/list.nhn?titleId=557673',
'http://comic.naver.com/webtoon/list.nhn?titleId=332797',
'http://comic.naver.com/webtoon/list.nhn?titleId=478261',
'http://comic.naver.com/webtoon/list.nhn?titleId=212694',
'http://comic.naver.com/webtoon/list.nhn?titleId=509093',
'http://comic.naver.com/webtoon/list.nhn?titleId=507274',
'http://comic.naver.com/webtoon/list.nhn?titleId=574303',
'http://comic.naver.com/webtoon/list.nhn?titleId=546620',
'http://comic.naver.com/webtoon/list.nhn?titleId=297796',
'http://comic.naver.com/webtoon/list.nhn?titleId=546622',
'http://comic.naver.com/webtoon/list.nhn?titleId=520599',
'http://comic.naver.com/webtoon/list.nhn?titleId=337964',
'http://comic.naver.com/webtoon/list.nhn?titleId=546623',
'http://comic.naver.com/webtoon/list.nhn?titleId=478262',
'http://comic.naver.com/webtoon/list.nhn?titleId=96908',
'http://comic.naver.com/webtoon/list.nhn?titleId=400741',
'http://comic.naver.com/webtoon/list.nhn?titleId=500943',
'http://comic.naver.com/webtoon/list.nhn?titleId=514917',
'http://comic.naver.com/webtoon/list.nhn?titleId=483613',
'http://comic.naver.com/webtoon/list.nhn?titleId=492659',
'http://comic.naver.com/webtoon/list.nhn?titleId=259893',
'http://comic.naver.com/webtoon/list.nhn?titleId=511454',
'http://comic.naver.com/webtoon/list.nhn?titleId=528782',
'http://comic.naver.com/webtoon/list.nhn?titleId=460689',
'http://comic.naver.com/webtoon/list.nhn?titleId=72939',
'http://comic.naver.com/webtoon/list.nhn?titleId=520600',
'http://comic.naver.com/webtoon/list.nhn?titleId=460686',
'http://comic.naver.com/webtoon/list.nhn?titleId=325629',
'http://comic.naver.com/webtoon/list.nhn?titleId=337962',
'http://comic.naver.com/webtoon/list.nhn?titleId=511446',
'http://comic.naver.com/webtoon/list.nhn?titleId=226807',
'http://comic.naver.com/webtoon/list.nhn?titleId=55143',
'http://comic.naver.com/webtoon/list.nhn?titleId=72497',
'http://comic.naver.com/webtoon/list.nhn?titleId=500944',
'http://comic.naver.com/webtoon/list.nhn?titleId=387518',
'http://comic.naver.com/webtoon/list.nhn?titleId=524353',
'http://comic.naver.com/webtoon/list.nhn?titleId=243316',
'http://comic.naver.com/webtoon/list.nhn?titleId=520598',
'http://comic.naver.com/webtoon/list.nhn?titleId=500942',
'http://comic.naver.com/webtoon/list.nhn?titleId=414612',
'http://comic.naver.com/webtoon/list.nhn?titleId=478249',
'http://comic.naver.com/webtoon/list.nhn?titleId=400737',
'http://comic.naver.com/webtoon/list.nhn?titleId=316912',
'http://comic.naver.com/webtoon/list.nhn?titleId=336945',
'http://comic.naver.com/webtoon/list.nhn?titleId=511445',
'http://comic.naver.com/webtoon/list.nhn?titleId=285855',
'http://comic.naver.com/webtoon/list.nhn?titleId=403631',
'http://comic.naver.com/webtoon/list.nhn?titleId=52946',
'http://comic.naver.com/webtoon/list.nhn?titleId=103759',
'http://comic.naver.com/webtoon/list.nhn?titleId=471284',
'http://comic.naver.com/webtoon/list.nhn?titleId=24530',
'http://comic.naver.com/webtoon/list.nhn?titleId=301382',
'http://comic.naver.com/webtoon/list.nhn?titleId=500945',
'http://comic.naver.com/webtoon/list.nhn?titleId=459546',
'http://comic.naver.com/webtoon/list.nhn?titleId=499334',
'http://comic.naver.com/webtoon/list.nhn?titleId=409628',
'http://comic.naver.com/webtoon/list.nhn?titleId=336944',
'http://comic.naver.com/webtoon/list.nhn?titleId=498158',
'http://comic.naver.com/webtoon/list.nhn?titleId=69296',
'http://comic.naver.com/webtoon/list.nhn?titleId=254132',
'http://comic.naver.com/webtoon/list.nhn?titleId=251575',
'http://comic.naver.com/webtoon/list.nhn?titleId=113119',
'http://comic.naver.com/webtoon/list.nhn?titleId=25913',
'http://comic.naver.com/webtoon/list.nhn?titleId=443421',
'http://comic.naver.com/webtoon/list.nhn?titleId=490549',
'http://comic.naver.com/webtoon/list.nhn?titleId=423376',
'http://comic.naver.com/webtoon/list.nhn?titleId=119877',
'http://comic.naver.com/webtoon/list.nhn?titleId=407142',
'http://comic.naver.com/webtoon/list.nhn?titleId=112931',
'http://comic.naver.com/webtoon/list.nhn?titleId=485489',
'http://comic.naver.com/webtoon/list.nhn?titleId=316913',
'http://comic.naver.com/webtoon/list.nhn?titleId=360613',
'http://comic.naver.com/webtoon/list.nhn?titleId=400735',
'http://comic.naver.com/webtoon/list.nhn?titleId=400736',
'http://comic.naver.com/webtoon/list.nhn?titleId=440447',
'http://comic.naver.com/webtoon/list.nhn?titleId=440437',
'http://comic.naver.com/webtoon/list.nhn?titleId=70046',
'http://comic.naver.com/webtoon/list.nhn?titleId=440439',
'http://comic.naver.com/webtoon/list.nhn?titleId=164320',
'http://comic.naver.com/webtoon/list.nhn?titleId=260510',
'http://comic.naver.com/webtoon/list.nhn?titleId=256855',
'http://comic.naver.com/webtoon/list.nhn?titleId=347685',
'http://comic.naver.com/webtoon/list.nhn?titleId=170785',
'http://comic.naver.com/webtoon/list.nhn?titleId=259937',
'http://comic.naver.com/webtoon/list.nhn?titleId=434644',
'http://comic.naver.com/webtoon/list.nhn?titleId=443422',
'http://comic.naver.com/webtoon/list.nhn?titleId=316908',
'http://comic.naver.com/webtoon/list.nhn?titleId=317365',
'http://comic.naver.com/webtoon/list.nhn?titleId=105533',
'http://comic.naver.com/webtoon/list.nhn?titleId=400738',
'http://comic.naver.com/webtoon/list.nhn?titleId=258207',
'http://comic.naver.com/webtoon/list.nhn?titleId=389845',
'http://comic.naver.com/webtoon/list.nhn?titleId=191347',
'http://comic.naver.com/webtoon/list.nhn?titleId=206149',
'http://comic.naver.com/webtoon/list.nhn?titleId=160461',
'http://comic.naver.com/webtoon/list.nhn?titleId=387517',
'http://comic.naver.com/webtoon/list.nhn?titleId=308802',
'http://comic.naver.com/webtoon/list.nhn?titleId=374970',
'http://comic.naver.com/webtoon/list.nhn?titleId=347686',
'http://comic.naver.com/webtoon/list.nhn?titleId=308801',
'http://comic.naver.com/webtoon/list.nhn?titleId=140444',
'http://comic.naver.com/webtoon/list.nhn?titleId=284940',
'http://comic.naver.com/webtoon/list.nhn?titleId=258206',
'http://comic.naver.com/webtoon/list.nhn?titleId=337963',
'http://comic.naver.com/webtoon/list.nhn?titleId=409100',
'http://comic.naver.com/webtoon/list.nhn?titleId=150388',
'http://comic.naver.com/webtoon/list.nhn?titleId=148778',
'http://comic.naver.com/webtoon/list.nhn?titleId=268859',
'http://comic.naver.com/webtoon/list.nhn?titleId=15568',
'http://comic.naver.com/webtoon/list.nhn?titleId=395444',
'http://comic.naver.com/webtoon/list.nhn?titleId=318992',
'http://comic.naver.com/webtoon/list.nhn?titleId=24995',
'http://comic.naver.com/webtoon/list.nhn?titleId=67235',
'http://comic.naver.com/webtoon/list.nhn?titleId=55150',
'http://comic.naver.com/webtoon/list.nhn?titleId=26671',
'http://comic.naver.com/webtoon/list.nhn?titleId=317362',
'http://comic.naver.com/webtoon/list.nhn?titleId=301378',
'http://comic.naver.com/webtoon/list.nhn?titleId=169081',
'http://comic.naver.com/webtoon/list.nhn?titleId=25735',
'http://comic.naver.com/webtoon/list.nhn?titleId=358286',
'http://comic.naver.com/webtoon/list.nhn?titleId=350217',
'http://comic.naver.com/webtoon/list.nhn?titleId=26309',
'http://comic.naver.com/webtoon/list.nhn?titleId=300957',
'http://comic.naver.com/webtoon/list.nhn?titleId=308751',
'http://comic.naver.com/webtoon/list.nhn?titleId=205528',
'http://comic.naver.com/webtoon/list.nhn?titleId=142911',
'http://comic.naver.com/webtoon/list.nhn?titleId=63455',
'http://comic.naver.com/webtoon/list.nhn?titleId=254143',
'http://comic.naver.com/webtoon/list.nhn?titleId=183558',
'http://comic.naver.com/webtoon/list.nhn?titleId=258205',
'http://comic.naver.com/webtoon/list.nhn?titleId=226806',
'http://comic.naver.com/webtoon/list.nhn?titleId=51006',
'http://comic.naver.com/webtoon/list.nhn?titleId=293521',
'http://comic.naver.com/webtoon/list.nhn?titleId=63453',
'http://comic.naver.com/webtoon/list.nhn?titleId=301377',
'http://comic.naver.com/webtoon/list.nhn?titleId=186812',
'http://comic.naver.com/webtoon/list.nhn?titleId=150387',
'http://comic.naver.com/webtoon/list.nhn?titleId=233265',
'http://comic.naver.com/webtoon/list.nhn?titleId=103391',
'http://comic.naver.com/webtoon/list.nhn?titleId=277235',
'http://comic.naver.com/webtoon/list.nhn?titleId=72499',
'http://comic.naver.com/webtoon/list.nhn?titleId=274400',
'http://comic.naver.com/webtoon/list.nhn?titleId=68684',
'http://comic.naver.com/webtoon/list.nhn?titleId=268858',
'http://comic.naver.com/webtoon/list.nhn?titleId=312979',
'http://comic.naver.com/webtoon/list.nhn?titleId=72938',
'http://comic.naver.com/webtoon/list.nhn?titleId=63129',
'http://comic.naver.com/webtoon/list.nhn?titleId=26084',
'http://comic.naver.com/webtoon/list.nhn?titleId=169082',
'http://comic.naver.com/webtoon/list.nhn?titleId=15640',
'http://comic.naver.com/webtoon/list.nhn?titleId=188197',
'http://comic.naver.com/webtoon/list.nhn?titleId=179704',
'http://comic.naver.com/webtoon/list.nhn?titleId=206146',
'http://comic.naver.com/webtoon/list.nhn?titleId=188199',
'http://comic.naver.com/webtoon/list.nhn?titleId=186814',
'http://comic.naver.com/webtoon/list.nhn?titleId=147175',
'http://comic.naver.com/webtoon/list.nhn?titleId=186813',
'http://comic.naver.com/webtoon/list.nhn?titleId=137706',
'http://comic.naver.com/webtoon/list.nhn?titleId=163295',
'http://comic.naver.com/webtoon/list.nhn?titleId=137710',
'http://comic.naver.com/webtoon/list.nhn?titleId=144956',
'http://comic.naver.com/webtoon/list.nhn?titleId=94761',
'http://comic.naver.com/webtoon/list.nhn?titleId=26086',
'http://comic.naver.com/webtoon/list.nhn?titleId=23182',
'http://comic.naver.com/webtoon/list.nhn?titleId=70045',
'http://comic.naver.com/webtoon/list.nhn?titleId=55169',
'http://comic.naver.com/webtoon/list.nhn?titleId=76759',
'http://comic.naver.com/webtoon/list.nhn?titleId=148975',
'http://comic.naver.com/webtoon/list.nhn?titleId=63454',
'http://comic.naver.com/webtoon/list.nhn?titleId=150389',
'http://comic.naver.com/webtoon/list.nhn?titleId=58219',
'http://comic.naver.com/webtoon/list.nhn?titleId=76758',
'http://comic.naver.com/webtoon/list.nhn?titleId=89098',
'http://comic.naver.com/webtoon/list.nhn?titleId=142910',
'http://comic.naver.com/webtoon/list.nhn?titleId=78805',
'http://comic.naver.com/webtoon/list.nhn?titleId=113584',
'http://comic.naver.com/webtoon/list.nhn?titleId=92106',
'http://comic.naver.com/webtoon/list.nhn?titleId=94760',
'http://comic.naver.com/webtoon/list.nhn?titleId=113587',
'http://comic.naver.com/webtoon/list.nhn?titleId=113121',
'http://comic.naver.com/webtoon/list.nhn?titleId=113586',
'http://comic.naver.com/webtoon/list.nhn?titleId=113582',
'http://comic.naver.com/webtoon/list.nhn?titleId=112933',
'http://comic.naver.com/webtoon/list.nhn?titleId=113581',
'http://comic.naver.com/webtoon/list.nhn?titleId=113588',
'http://comic.naver.com/webtoon/list.nhn?titleId=113535',
'http://comic.naver.com/webtoon/list.nhn?titleId=113585',
'http://comic.naver.com/webtoon/list.nhn?titleId=25898',
'http://comic.naver.com/webtoon/list.nhn?titleId=132459',
'http://comic.naver.com/webtoon/list.nhn?titleId=73352',
'http://comic.naver.com/webtoon/list.nhn?titleId=58293',
'http://comic.naver.com/webtoon/list.nhn?titleId=26205',
'http://comic.naver.com/webtoon/list.nhn?titleId=65410',
'http://comic.naver.com/webtoon/list.nhn?titleId=26107',
'http://comic.naver.com/webtoon/list.nhn?titleId=52993',
'http://comic.naver.com/webtoon/list.nhn?titleId=72498',
'http://comic.naver.com/webtoon/list.nhn?titleId=70920',
'http://comic.naver.com/webtoon/list.nhn?titleId=69297',
'http://comic.naver.com/webtoon/list.nhn?titleId=26074',
'http://comic.naver.com/webtoon/list.nhn?titleId=26216',
'http://comic.naver.com/webtoon/list.nhn?titleId=67340',
'http://comic.naver.com/webtoon/list.nhn?titleId=62251',
'http://comic.naver.com/webtoon/list.nhn?titleId=25904',
'http://comic.naver.com/webtoon/list.nhn?titleId=66913',
'http://comic.naver.com/webtoon/list.nhn?titleId=26115',
'http://comic.naver.com/webtoon/list.nhn?titleId=69113',
'http://comic.naver.com/webtoon/list.nhn?titleId=26458',
'http://comic.naver.com/webtoon/list.nhn?titleId=57875',
'http://comic.naver.com/webtoon/list.nhn?titleId=26114',
'http://comic.naver.com/webtoon/list.nhn?titleId=26431',
'http://comic.naver.com/webtoon/list.nhn?titleId=55120',
'http://comic.naver.com/webtoon/list.nhn?titleId=22896',
'http://comic.naver.com/webtoon/list.nhn?titleId=26473',
'http://comic.naver.com/webtoon/list.nhn?titleId=26460',
'http://comic.naver.com/webtoon/list.nhn?titleId=25897',
'http://comic.naver.com/webtoon/list.nhn?titleId=26456',
'http://comic.naver.com/webtoon/list.nhn?titleId=26310',
'http://comic.naver.com/webtoon/list.nhn?titleId=15441',
'http://comic.naver.com/webtoon/list.nhn?titleId=26440',
'http://comic.naver.com/webtoon/list.nhn?titleId=26101',
'http://comic.naver.com/webtoon/list.nhn?titleId=25695',
'http://comic.naver.com/webtoon/list.nhn?titleId=50422',
'http://comic.naver.com/webtoon/list.nhn?titleId=22043',
'http://comic.naver.com/webtoon/list.nhn?titleId=25734',
'http://comic.naver.com/webtoon/list.nhn?titleId=26144',
'http://comic.naver.com/webtoon/list.nhn?titleId=25050',
'http://comic.naver.com/webtoon/list.nhn?titleId=25714',
'http://comic.naver.com/webtoon/list.nhn?titleId=22052',
'http://comic.naver.com/webtoon/list.nhn?titleId=25517',
'http://comic.naver.com/webtoon/list.nhn?titleId=24525',
'http://comic.naver.com/webtoon/list.nhn?titleId=24777',
'http://comic.naver.com/webtoon/list.nhn?titleId=22037',
'http://comic.naver.com/webtoon/list.nhn?titleId=24475',
'http://comic.naver.com/webtoon/list.nhn?titleId=23183',
'http://comic.naver.com/webtoon/list.nhn?titleId=22090',
'http://comic.naver.com/webtoon/list.nhn?titleId=20762',
'http://comic.naver.com/webtoon/list.nhn?titleId=15439',
'http://comic.naver.com/webtoon/list.nhn?titleId=15395',
'http://comic.naver.com/webtoon/list.nhn?titleId=22073',
'http://comic.naver.com/webtoon/list.nhn?titleId=15938',
'http://comic.naver.com/webtoon/list.nhn?titleId=15569'
]
class MainParser:
    def __init__(self, func=None):
        if func:
            self.parse_url = func

    def parse_url(self, _url):
        print("미구현")
        print(_url)

def naver_parser(_url):
    number = 0
    stop = 1
    list2 = None
    # f = open(file_path, 'w', encoding='utf-8')
    while stop == 1:
        number += 1
        response = requests.get(_url + str(number))
        soup = BeautifulSoup(response.text, 'html.parser')
        list = soup.select('table tr')
        cnt = 1
        data = ''
        if list != list2:
            for li in list:
                if _url + str(number) != "http://comic.naver.com/webtoon/list.nhn?titleId=25455&weekday=tue&page="+str(number) and _url  + str(number) != 'http://comic.naver.com/webtoon/list.nhn?titleId=20853&weekday=tue&page='+str(number):
                    if cnt < 3:
                        cnt = cnt + 1
                        continue
                    li2 = li.find('img')['src']
                    title = li.find_all('a')
                    href = title[1]['href']
                    date = li.find_all('td')
                    print(li2, title[1].text, 'http://comic.naver.com' + href, date[3].text)
                    data = "%s, %s, %s, %s\n" % (li2, title[1].text, 'http://comic.naver.com' + href, date[3].text)
                    f.write(data)
                else:
                    if cnt < 4:
                        cnt = cnt + 1
                        continue
                    li2 = li.find('img')['src']
                    title = li.find_all('a')
                    href = title[1]['href']
                    date = li.find_all('td')
                    print(li2, title[1].text, 'http://comic.naver.com' + href, date[3].text)
                    data = "%s, %s, %s, %s\n" % (li2, title[1].text, 'http://comic.naver.com' + href, date[3].text)
                    f.write(data)
        else:
            break
        list2 = list

    return data

parser_select_dict = {
    'comic.naver.com': naver_parser
}

now = datetime.now()
file_path = datetime.strftime(now, "./toon.txt")

# def scraping():
data = ''
f = open(file_path, 'w', encoding='utf-8')
for url in urls:
    parsed_url = urlparse(url)
    print(parsed_url[1], url)
    func = parser_select_dict[parsed_url[1]]
    parser = MainParser(func)
    # f.write(parser.parse_url(url))
    print(parser.parse_url(url))
f.close()
# 아래는 반복실행을 위한 코드
# if __name__ == '__main__':
#     scheduler = BlockingScheduler()
#     print("START")
#     scheduler.add_job(scraping, 'interval', seconds=30)
#
#     try:
#         scheduler.start()
#     except(KeyboardInterrupt, SystemExit):
#         print("EXIT")
#         pass







